AWSTemplateFormatVersion: '2010-09-09'
Description: 'saga-ec

  Sample SAM Template for saga-ec

  '
Globals:
  Function:
    Environment:
      Variables:
        TABLE_ORDER: SagaEcOrder
    MemorySize: 256
    Runtime: python3.6
    Timeout: 15
Resources:
  HelloWorldFunction:
    Properties:
      CodeUri: s3://sam.saga-ec/67239d35f513ed02f93e7fc9c6b26f68
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Api:
          Properties:
            Method: get
            Path: /hello
          Type: Api
      Handler: lambda_function.lambda_handler
      Role:
        Fn::GetAtt:
        - LambdaToDynamoDbIamRole
        - Arn
      Runtime: python3.6
    Type: AWS::Serverless::Function
  LambdaToDynamoDbIamRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
        Version: '2012-10-17'
      Policies:
      - PolicyDocument:
          Statement:
          - Action: dynamodb:*
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: billing_mail_for_lambda
    Type: AWS::IAM::Role
  SagaEcOrderCreateFunction:
    Properties:
      CodeUri: s3://sam.saga-ec/d2d8067257b123a24d1d073f5651e5a3
      Events:
        Api:
          Properties:
            Method: post
            Path: /orders
          Type: Api
      Handler: order.create
      Role: arn:aws:iam::725683553534:role/saga-ec-Lambda
      Runtime: python3.6
    Type: AWS::Serverless::Function
  SagaEcOrderListFunction:
    Properties:
      CodeUri: s3://sam.saga-ec/d2d8067257b123a24d1d073f5651e5a3
      Events:
        Api:
          Properties:
            Method: get
            Path: /orders
          Type: Api
      Handler: order.list
      Role: arn:aws:iam::725683553534:role/saga-ec-Lambda
      Runtime: python3.6
    Type: AWS::Serverless::Function
  SagaEcOrderReadFunction:
    Properties:
      CodeUri: s3://sam.saga-ec/d2d8067257b123a24d1d073f5651e5a3
      Events:
        Api:
          Properties:
            Method: get
            Path: /orders/{txId}
          Type: Api
      Handler: order.read
      Role: arn:aws:iam::725683553534:role/saga-ec-Lambda
      Runtime: python3.6
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
